// Interfaces para la estructura de datos de productos
// Preparado para nueva ingesta de datos

export interface ProductImage {
  filename: string;
  path: string;
  extension: string;
  size: number;
  exists: boolean;
  webp?: string;
  fallback?: string;
  thumbnail?: string;
  alt?: string;
  width?: number;
  height?: number;
}

export interface ProductPDF {
  filename: string;
  path: string;
  size: string;
  downloadUrl: string;
  exists: boolean;
  url?: string;
  lastModified?: string;
}

export interface ProductAssets {
  id?: string;
  markdown?: {
    path: string;
    exists: boolean;
    content?: string;
  };
  image?: ProductImage;
  images?: {
    main: ProductImage;
    gallery?: ProductImage[];
  };
  pdf?: ProductPDF;
}

// Translation interfaces for multilingual support
export interface ProductTranslationContent {
  name: string;
  description: string;
  benefits?: string[];
  presentation?: string[];
  specifications?: Array<{
    key: string;
    value: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
    keywords?: string[];
  };
}

export interface ProductTranslations {
  es: ProductTranslationContent;
  en?: ProductTranslationContent;
  pt?: ProductTranslationContent;
}

export interface OptimizedProduct {
  id: string;
  slug: string;
  codigo: string;
  productCode?: string;
  name: string;
  description: string;
  specifications: Array<{
    key: string;
    value: string;
  }>;
  category: string;
  subcategory?: string;
  clasificacion?: number;
  image?: string;
  assets: ProductAssets;
  metadata: ProductMetadata;
  seo?: {
    title?: string;
    description?: string;
    keywords?: string[];
  };
  benefits?: string[];
  presentation?: string[];
  tags?: string[];
  // New translation support
  translations?: ProductTranslations;
}

export interface ProductMetadata {
  lastModified?: Date;
  autoGenerated?: boolean;
  needsReview?: boolean;
  validationIssues?: string[];
  completenessScore?: number;
  featured?: boolean;
  priority?: number;
  lastUpdated?: string;
  searchTags?: string[];
  category?: string;
  subcategory?: string;
}

export interface ProductRegistry {
  products: OptimizedProduct[];
  categories: string[];
  totalCount: number;
  lastUpdated: Date;
}

export interface ProductFilter {
  category?: string;
  subcategory?: string;
  searchQuery?: string;
  tags?: string[];
  featured?: boolean;
  hasDatasheet?: boolean;
}

export interface ProductSearchResult {
  products: OptimizedProduct[];
  totalCount: number;
  hasMore: boolean;
  filters: ProductFilter;
}

// Mapeo de categorías a clasificaciones numéricas
export const CLASIFICACIONES = {
  aditivos: 1,
  alimentos: 2,
  probioticos: 3,
  quimicos: 4,
  equipos: 5
} as const;

export type ProductCategory = keyof typeof CLASIFICACIONES;

// Language support
export type SupportedLanguage = 'es' | 'en' | 'pt';

// Translation status tracking
export interface TranslationStatus {
  language: SupportedLanguage;
  completed: boolean;
  quality: 'auto' | 'human' | 'reviewed';
  lastUpdated: Date;
  translator?: string;
}

/**
 * Tipos para integración WordPress API
 * Agregados en: 2025-11-07 (commit 014baa81+)
 */

export interface WordPressAPIResponse {
  products: OptimizedProduct[];
  total: number;
  totalPages: number;
}

export interface APIError {
  message: string;
  code?: string;
  status?: number;
}

// Extended ProductImage with WordPress URL support
export interface ProductImageWithURL extends ProductImage {
  url?: string;  // Dynamic URL from WordPress
}

// Extended ProductPDF with WordPress URL support
export interface ProductPDFWithURL extends ProductPDF {
  url?: string;  // Dynamic URL from WordPress
}