import React from 'react';
import { render, screen, fireEvent, waitFor } from '../../test-utils';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import ProductoDetalle from '../ProductoDetalle';

// Mock de react-router-dom hooks specifically for this test
vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual('react-router-dom');
  return {
    ...actual,
    useParams: () => ({ categorySlug: 'alimentos', slug: 'test-product-1' }),
    useNavigate: () => vi.fn(),
  };
});

// Mock de Swiper
vi.mock('swiper/react', () => ({
  Swiper: ({ children }: { children: React.ReactNode }) => <div data-testid="swiper">{children}</div>,
  SwiperSlide: ({ children }: { children: React.ReactNode }) => <div data-testid="swiper-slide">{children}</div>,
}));

// Mock de Swiper modules
vi.mock('swiper/modules', () => ({
  Navigation: {},
  Pagination: {},
  Autoplay: {},
}));

// Mock de getAllProducts
vi.mock('../../data/products', () => ({
  getAllProducts: () => [mockProduct],
}));

// Mock de product translations
vi.mock('../../data/products/product-translations', () => ({
  getProductTranslation: () => null,
}));

// Mock de Layout
vi.mock('../../components/Layout', () => ({
  default: ({ children }: { children: React.ReactNode }) => <div data-testid="layout">{children}</div>
}));

// Mock de StaticHero
vi.mock('../../components/StaticHero', () => ({
  default: ({ title }: { title: string }) => <div data-testid="static-hero">{title}</div>
}));

// Mock de NuestrasMarcas
vi.mock('../../components/NuestrasMarcas', () => ({
  default: () => <div data-testid="nuestras-marcas">Nuestras Marcas</div>
}));

// Mock de Breadcrumbs
vi.mock('../../components/Breadcrumbs', () => ({
  default: () => <div data-testid="breadcrumbs">Breadcrumbs</div>
}));

const mockProduct = {
  id: 'test-product-1',
  slug: 'test-product-1',
  codigo: 'TEST-001',
  name: 'Test Product 1',
  description: 'Test description 1',
  category: 'alimentos',
  specifications: [
    { key: 'Composición', value: 'Test composition' },
    { key: 'Dosificación', value: 'Test dosage' },
    { key: 'Aplicación', value: 'Test application' }
  ],
  benefits: ['Benefit 1', 'Benefit 2'],
  presentation: ['Test presentation'],
  assets: {
    image: {
      filename: 'test-image-1.jpg',
      path: '/test-image-1.jpg',
      extension: 'jpg',
      size: 1024,
      exists: true,
      alt: 'Test Product 1'
    },
    pdf: {
      filename: 'test-pdf-1.pdf',
      path: '/test-pdf-1.pdf',
      size: '2MB',
      downloadUrl: '/test-pdf-1.pdf',
      exists: true
    }
  },
  metadata: {
    lastModified: new Date(),
    autoGenerated: false,
    completenessScore: 100
  }
};

describe('ProductoDetalle', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders product details correctly', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByText('Test Product 1')[0]).toBeInTheDocument();
    // Use getAllByTestId to account for multiple Layout components rendered
    const layoutElements = screen.getAllByTestId('layout');
    expect(layoutElements.length).toBeGreaterThan(0);
    expect(screen.getByAltText('Test Product 1')).toBeInTheDocument();
  });

  it('displays product information sections', () => {
    render(<ProductoDetalle />);

    // Check if main sections are present using getAllBy to handle duplicates
    const breadcrumbs = screen.getAllByTestId('breadcrumbs');
    expect(breadcrumbs.length).toBeGreaterThan(0);
    const descriptions = screen.getAllByText((content, element) => content.includes('Descripción') || content === 'Descripción');
    expect(descriptions.length).toBeGreaterThan(0);
    const specifications = screen.getAllByText('Especificaciones');
    expect(specifications.length).toBeGreaterThan(0);
  });

  it('handles missing product gracefully', () => {
    // This test needs its own mock that returns empty array
    vi.doMock('../../data/products', () => ({
      getAllProducts: () => [],
    }));

    render(<ProductoDetalle />);

    // Should show product not found message
    const layouts = screen.getAllByTestId('layout');
    expect(layouts.length).toBeGreaterThan(0);
  });

  it('displays product details when available', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByText('Test Product 1')[0]).toBeInTheDocument();
    expect(screen.getAllByText('Test description 1')[0]).toBeInTheDocument();
  });

  it('renders download button for datasheet', () => {
    render(<ProductoDetalle />);

    const downloadButton = screen.getAllByText('Descargar Ficha Técnica (PDF)')[0];
    expect(downloadButton.closest('a')).toHaveAttribute('href', expect.stringContaining('.pdf'));
  });

  it('handles image loading', () => {
    render(<ProductoDetalle />);

    const images = screen.getAllByAltText('Test Product 1');
    expect(images[0]).toBeInTheDocument();
    expect(images[0]).toHaveAttribute('src', '/test-image-1.jpg');
  });

  it('renders product image', () => {
    render(<ProductoDetalle />);

    const images = screen.getAllByAltText('Test Product 1');
    expect(images[0]).toBeInTheDocument();
    expect(images[0]).toHaveAttribute('src', '/test-image-1.jpg');
  });

  it('displays product description', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByText('Test description 1')[0]).toBeInTheDocument();
  });

  it('renders nuestras marcas component', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByTestId('nuestras-marcas')[0]).toBeInTheDocument();
  });

  it('displays complete product information', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByText('Test Product 1')[0]).toBeInTheDocument();
    expect(screen.getAllByText((content) => content.includes('TEST-001'))[0]).toBeInTheDocument();
    expect(screen.getAllByText('Test description 1')[0]).toBeInTheDocument();
    expect(screen.getAllByText('Alimentos')[0]).toBeInTheDocument();
  });

  it('displays tab navigation', () => {
    render(<ProductoDetalle />);

    expect(screen.getAllByText((content) => content.includes('Descripción'))[0]).toBeInTheDocument();
    expect(screen.getAllByText('Especificaciones')[0]).toBeInTheDocument();
    expect(screen.getAllByText('Beneficios')[0]).toBeInTheDocument();
    expect(screen.getAllByText('Presentación')[0]).toBeInTheDocument();
  });
});