/**
 * ProductCodeMapper - Utilidad para mapear códigos de productos
 * Extrae códigos desde autoGenerated.ts y los asocia con productos legacy
 */

import { PRODUCTS_REGISTRY } from '../data/products';

// Cache para mapeo de códigos
const codeCache = new Map<string, string>();

/**
 * Inicializa el cache de códigos desde el registry auto-generado
 */
const initializeCodeCache = (): void => {
  if (codeCache.size > 0) return; // Ya inicializado
  
  PRODUCTS_REGISTRY.forEach(product => {
    // Mapear por ID del producto
    codeCache.set(product.id, product.codigo);
    
    // También mapear por nombre para casos donde el ID no coincida exactamente
    const normalizedName = product.name.toUpperCase().replace(/\s+/g, '_');
    codeCache.set(normalizedName, product.codigo);
  });
  
  console.log(`📋 ProductCodeMapper: ${codeCache.size / 2} códigos de productos cargados`);
};

/**
 * Obtiene el código de un producto por su ID
 */
export const getProductCode = (productId: string): string | undefined => {
  initializeCodeCache();
  return codeCache.get(productId);
};

/**
 * Obtiene el código de un producto por su nombre
 */
export const getProductCodeByName = (productName: string): string | undefined => {
  initializeCodeCache();
  const normalizedName = productName.toUpperCase().replace(/\s+/g, '_');
  return codeCache.get(normalizedName);
};

/**
 * Formatea el display del producto con código
 * Retorna: "[CÓDIGO] NOMBRE" o solo "NOMBRE" si no hay código
 */
export const formatProductDisplay = (productName: string, productId?: string, codigo?: string): string => {
  // Si ya viene el código directamente, usarlo
  if (codigo) {
    return `[${codigo}] ${productName}`;
  }
  
  // Intentar obtenerlo por ID
  let code = productId ? getProductCode(productId) : undefined;
  
  // Si no se encuentra por ID, intentar por nombre
  if (!code) {
    code = getProductCodeByName(productName);
  }
  
  return code ? `[${code}] ${productName}` : productName;
};

/**
 * Obtiene todos los códigos disponibles (útil para debugging)
 */
export const getAllProductCodes = (): Record<string, string> => {
  initializeCodeCache();
  const result: Record<string, string> = {};
  
  PRODUCTS_REGISTRY.forEach(product => {
    result[product.id] = product.codigo;
  });
  
  return result;
};

/**
 * Verifica si un producto tiene código asignado
 */
export const hasProductCode = (productId: string): boolean => {
  return getProductCode(productId) !== undefined;
};

/**
 * Extrae solo el código de un display formateado
 * "[AD001] PRODUCTO" -> "AD001"
 */
export const extractCodeFromDisplay = (displayText: string): string | undefined => {
  const match = displayText.match(/^\[([^\]]+)\]/);
  return match ? match[1] : undefined;
};

/**
 * Extrae solo el nombre de un display formateado
 * "[AD001] PRODUCTO" -> "PRODUCTO"
 */
export const extractNameFromDisplay = (displayText: string): string => {
  const match = displayText.match(/^\[[^\]]+\]\s*(.+)$/);
  return match ? match[1] : displayText;
};