// Productos EQUIPOS generados automáticamente
// Total de productos: 43
// Generado: 2025-07-21T23:39:18.565Z

export const equiposProducts = [
  {
    id: "prod-519",
    number: 519,
    slug: "manguera-de-vinil-transparente",
    name: "MANGUERA DE VINIL TRANSPARENTE",
    category: "equipos",
    subcategory: "accesorios",
    image: "/assets/images/productos/equipos/EQ013.png",
    gallery: ["/assets/images/productos/equipos/EQ013.png"],
    description: "Aprobado por la FDA, de muy alta calidad con un diámetro ligeramente más grande y pared más pesada que la tubería de acuario.",
    specifications: "Modelo: TP30HD Longitud: 100 pie Diámetro interior: 3/16 pulgadas Diámetro exterior: 5/16 pulgadas PSI: 40",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ013_ficha.pdf",
    productCode: "EQ013",
    benefits: "Este tubo tiene una capacidad nominal de 36 psi a 22 °C (72 °F).",
    presentation: "Rollos de 31 metros."
  },
  {
    id: "prod-520",
    number: 520,
    slug: "manguera-difusora",
    name: "MANGUERA DIFUSORA",
    category: "equipos",
    subcategory: "accesorios",
    image: "/assets/images/productos/equipos/EQ038.png",
    gallery: ["/assets/images/productos/equipos/EQ038.png"],
    description: "Para obtener un ambiente adecuado en el estanque, la manguera difusora se debe ubicar de acuerdo a la forma del mismo: Estanque circular: Debe ser ubicada de...",
    specifications: "Diámetro externo: 2,54cm Diámetro interno: 1,27cm Grosor de la pared: 0,64cm Peso: 0,33 kg/m Longitud del rollo: 61m Peso del rollo: 20kg Presión de la rotura: 5,62 kgs/cm2 Flujo de aire: 0,037m3/min/m",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ038_ficha.pdf",
    productCode: "EQ038",
    benefits: "- La manguera difusora Aerotube está compuesta por un material de polietileno poroso. - Permite emitir micro burbujas y mantener alrededor del 90% a 95% del nivel de oxígeno en el agua.",
    presentation: "Por metro"
  },
  {
    id: "prod-521",
    number: 521,
    slug: "blowers-gast",
    name: "BLOWERS GAST",
    category: "equipos",
    subcategory: "aireacion",
    image: "/assets/images/productos/equipos/EQ035.png",
    gallery: ["/assets/images/productos/equipos/EQ035.png"],
    description: "Modelos con motor estándar.",
    specifications: "[Especificaciones pendientes de completar]",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ035_ficha.pdf",
    productCode: "EQ035",
    benefits: "- Construcción robusta de aluminio y hierro fundido. - Contienen una nueva grasa de poliurea que extiende la vida del rodamiento y ofrece una resistencia superior al lavado, oxidación y corrosión. - Motores multi-voltaje a prueba de explosiones.",
    presentation: "[Información de presentación pendiente]"
  },
  {
    id: "prod-522",
    number: 522,
    slug: "blowers-all-star",
    name: "BLOWERS ALL STAR",
    category: "equipos",
    subcategory: "aireacion",
    image: "",
    gallery: [],
    description: "",
    specifications: "[Especificaciones pendientes de completar]",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ036_ficha.pdf",
    productCode: "EQ036",
    benefits: "- Rendimiento de alta eficiencia - Motor AC de jaula de 2 polos IP 54 TEFC - Aislamiento clase H",
    presentation: "[Información de presentación pendiente]"
  },
  {
    id: "prod-523",
    number: 523,
    slug: "piedras-difusoras",
    name: "PIEDRAS DIFUSORAS",
    category: "equipos",
    subcategory: "aireacion",
    image: "/assets/images/productos/equipos/EQ037.png",
    gallery: ["/assets/images/productos/equipos/EQ037.png"],
    description: "Los difusores de aire son ideales para producir una emisión homogénea de pequeñas burbujas en su acuario de agua dulce o salada. Con estos difusores podrá cr...",
    specifications: "- Está fabricado con polímeros plásticos y cerámica de alta calidad y durabilidad. - Químicamente inertes al agua. - Esta línea ofrece tres modelos rectangulares para adaptarse a las necesidades puntuales de cada aplicación. - Su conexión es de diámetro standard para manguera de 4/6 milímetros.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ037_ficha.pdf",
    productCode: "EQ037",
    benefits: "Todos los modelos de difusores cerámicos presentan flotabilidad negativa. Esto es una gran ventaja a la hora de mantenerlos en el fondo del acuario sin la necesidad de usar un lastre.",
    presentation: "- Piedras difusoras AS15S - Piedras difusoras AS3 (5x2.5x4) - Piedras difusoras AS8L (8x4x4) - Bubblemac Barb #0020 - Bubblemac Barb #0030 - Bubblemac Barb #0020F"
  },
  {
    id: "prod-524",
    number: 524,
    slug: "balanzas-ohaus",
    name: "BALANZAS OHAUS",
    category: "equipos",
    subcategory: "balanzas",
    image: "",
    gallery: [],
    description: "Balanzas OHAUS de diferentes dimensiones y capacidades bajo pedido.",
    specifications: "- Pantalla LCD de alto contraste que indica claramente datos de peso y aplicaciones, así como indicadores de estabilidad, condiciones de sobrecarga y estado de las baterías. - Botones para su fácil operación. - Platillo redondo o cuadrado de acero inoxidable. - Gancho integrado para pesar por debajo de la balanza. - Conectividad USB o RS232 opcionales. - Soporte de seguridad integral. - Apagado automático.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ031_ficha.pdf",
    productCode: "EQ031",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "- Balanza Scout Pro 400 x 0.1 g. - Balanza Scout Pro 600 x 0.1 g. - Balanza Scout Pro 2000 x 0.1 g. - Balanza Scout Pro 1200 x 0.1 g. - Balanza Triple Brazo con Dia"
  },
  {
    id: "prod-525",
    number: 525,
    slug: "cinta-industrial-prime",
    name: "CINTA INDUSTRIAL PRIME",
    category: "equipos",
    subcategory: "cintas",
    image: "/assets/images/productos/equipos/EQ040.png",
    gallery: ["/assets/images/productos/equipos/EQ040.png"],
    description: "La cinta industrial de color negro es fabricado con material sensible a la presión y contiene adhesivos de alta calidad, siendo ideal para las reparaciones t...",
    specifications: "- La superficie por pegar debe estar limpia y seca. La cinta no se adherirá si las superficies no están preparadas adecuadamente, superficies sucias o húmedas. - Deberán limpiarse en su totalidad con agua, toallas de papel, trapos secos u otros materiales que preparen la superficie para pegar la cinta. - Las acumulaciones de polvo también deben eliminarse para asegurar un pegado seguro. - Para una óptima adhesión se prefiere una temperatura en la superficie que esté por encima de los 10 a 15º C. - Si está por debajo de este rango, se debe utilizar una fuente de calor, como un soplador de aire caliente de uso industrial que es un método recomendado.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ040_ficha.pdf",
    productCode: "EQ040",
    benefits: "- No es sensible a altas temperaturas ambientales, ni exposición UV y a la hu- medad. - Es de grado alimenticio, no tóxico para producción acuícola. - Alta resistencia, la cinta no se puede retirar fácilmente una vez adherido. - Revestimiento antiadherente de papel.",
    presentation: "Ancho: 10 cm Largo: 15 m Peso estándar: 1,4 kg Espesor del adhesivo: 0,51 mm"
  },
  {
    id: "prod-526",
    number: 526,
    slug: "bolso-filtrantes-de-polipropileno",
    name: "BOLSO FILTRANTES DE POLIPROPILENO",
    category: "equipos",
    subcategory: "filtros",
    image: "/assets/images/productos/equipos/EQ039.png",
    gallery: ["/assets/images/productos/equipos/EQ039.png"],
    description: "El proceso de líquidos con bolsas filtrantes funciona como un filtro de profundidad y es muy recomendable para filtrar líquidos con un gran número de partícu...",
    specifications: "- Clasificaciones de filtración de 1 - 5 - 10 - 50 micras. - Alta capacidad de retención. - Amplia compatibilidad química. - Filtración económica. - Material principal de fabricación: Polipropileno.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ039_ficha.pdf",
    productCode: "EQ039",
    benefits: "Su principal ventaja, es su alta capacidad de retención de partículas y su alto flujo. Siendo una de las mejores soluciones económicas para muchas aplicaciones de filtración de líquidos.",
    presentation: "- Bolso filtrante corto 1 micra. - Bolso filtrante largo 1 micra. - Bolso filtrante corto 5 micras. - Bolso filtrante largo 5 micras. - Bolso filtrante largo 10 micras. - Bolso filtrante largo 50 micras."
  },
  {
    id: "prod-527",
    number: 527,
    slug: "waterlink-spin-touch",
    name: "WATERLINK SPIN TOUCH",
    category: "equipos",
    subcategory: "general",
    image: "",
    gallery: [],
    description: "Fotómetro digital avanzado para pruebas rápidas y precisas en agua dulce y salada. Utiliza discos prellenados (SpinDisk™) para ejecutar de 8 a 10 pruebas sim...",
    specifications: "Características Principales • Realiza hasta 10 pruebas simultáneas en 2 minutos • Registro automático de fecha, hora y resultados • Panel de monitoreo con alertas e historial por estanque • Compatible con app WaterLink® (iOS y Android) Datos Técnicos • Muestra requerida: < 3 ml • Tipo de disco: SpinDisk™ (descartable) • Tipo de agua: Dulce y salada • Visualización: Resultados en tiempo real",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ002_ficha.pdf",
    productCode: "EQ002",
    benefits: "Ahorra tiempo con resultados rápidos y confiables • Reduce errores humanos con reactivos premedidos • Facilita el control y seguimiento de calidad del agua • Mejora la toma de decisiones mediante historial y alertas",
    presentation: "Equipo portátil con discos individuales. No requiere condiciones especiales de almacenamiento."
  },
  {
    id: "prod-528",
    number: 528,
    slug: "oxigenometro-disuelto-do-120",
    name: "OXIGENÓMETRO - Disuelto DO -120",
    category: "equipos",
    subcategory: "general",
    image: "/assets/images/productos/equipos/EQ005.png",
    gallery: ["/assets/images/productos/equipos/EQ005.png"],
    description: "Oxigenómetro portátil japonés de alta precisión para mediciones de oxígeno disuelto y temperatura en campo. Equipado con sensor galvánico y carcasa resistent...",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a caídas, flota en agua • Pantalla LCD retroiluminada • Registro de datos con fecha y hora • Auto-hold y mensajes de diagnóstico • Apagado automático programable (1 a 30 min) • Compatible con laptops vía salida RS232C • Memoria de hasta 1000 lecturas Datos Técnicos • Rango oxígeno disuelto: 0.0 – 20.00 mg/L (0.0 – 200.0%) • Resolución oxígeno: 0.01 mg/L o 0.1% • Precisión oxígeno: ±0.1 mg/L • Rango de temperatura: -30.0 °C a 130.0 °C • Resolución temperatura: 0.1 °C • Precisión temperatura: ±0.4 °C • Compensación salinidad: 0 – 40 ppt • Compensación barométrica: Sí • Calibración: 1 o 2 puntos • Sensor: Galvánico con sensor de temperatura integrado • Salida de datos: RS232C • Conectores: BNC y jack tipo phono Alimentación y Autonomía • 2 baterías AAA (LR03), Ni-H recargables o adaptador • Duración batería: > 500 horas",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ005_ficha.pdf",
    productCode: "EQ005",
    benefits: "Ideal para trabajos prolongados en campo por su resistencia y duración de batería • Alta precisión y confiabilidad en condiciones extremas • Capacidad de registrar y exportar datos con sello de fecha y hora • Fácil lectura y uso incluso en entornos oscuros o húmedos",
    presentation: "Kit incluye medidor DO120, sensor galvánico 9551-20D con cable de 2 m. No requiere condiciones especiales de almacenamiento ni refrigeración."
  },
  {
    id: "prod-529",
    number: 529,
    slug: "salinometro-11",
    name: "SALINÓMETRO -11",
    category: "equipos",
    subcategory: "general",
    image: "/assets/images/productos/equipos/EQ010.png",
    gallery: ["/assets/images/productos/equipos/EQ010.png"],
    description: "Salinómetro portátil de alta precisión con sensor plano, ideal para mediciones rápidas y confiables de salinidad en agua de mar, soluciones nutritivas y mues...",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a golpes • Pantalla LCD monocromática con retroiluminación • Sensor plano reemplazable • Auto Hold y Auto Estable • Apagado automático (30 min) • Indicador de batería baja • Reconocimiento automático de buffer • Calibración automática de temperatura • Sensor robusto ideal para campo y laboratorio. Construcción y Alimentación • Material: Carcasa de Epoxi ABS / Sensor plano • Dimensiones: 164 × 29 × 20 mm • Peso: Aprox. 50 g (incluyendo baterías) • Alimentación: 2 baterías CR2032 • Duración: Aprox. 400 horas de uso continuo sin retroiluminación",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ010_ficha.pdf",
    productCode: "EQ010",
    benefits: "• Ideal para mediciones rápidas y precisas con muy poco volumen de muestra. • Apto para condiciones de campo exigentes gracias a su resistencia al agua, polvo y golpes. • Calibración y operación sencillas, incluso para personal no técnico. • Alta portabilidad, ideal para monitoreo directo de salinidad en acuicultura, alimentos, aguas residuales y más.",
    presentation: "• Soluciones de calibración a 0.5% y 5.0% (14 ml c/u) • Solución de tratamiento de electrodo (4 ml) • 2 baterías CR2032 • Pipeta • Manual de instrucciones • Estuche portátil"
  },
  {
    id: "prod-530",
    number: 530,
    slug: "salinometro-vee-gee-stx-3",
    name: "SALINÓMETRO VEE GEE STX-3",
    category: "equipos",
    subcategory: "general",
    image: "/assets/images/productos/equipos/EQ011.png",
    gallery: ["/assets/images/productos/equipos/EQ011.png"],
    description: "Refractómetro manual de alta precisión diseñado para medir la concentración de sal (ppt) y la gravedad específica (GE) en agua de mar. Fabricado con material...",
    specifications: "Rango de medición: • Salinidad: 0 a 100 ppt (partes por mil) • Gravedad específica: 1.000 a 1.070 Compensación de temperatura: • Automática (ATC), permite lecturas precisas sin importar la temperatura ambiente Material y diseño: • Prisma de vidrio óptico en carcasa metálica • Cuerpo de metal duradero con recubrimiento exterior de caucho • Empuñadura de goma que protege contra el calor de la mano y asegura mediciones estables • Diseño tipo telescopio aerodinámico • Dimensiones: 40 × 40 × 185 mm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ011_ficha.pdf",
    productCode: "EQ011",
    benefits: "Precisión inmediata sin necesidad de energía eléctrica. • Alta durabilidad y portabilidad para uso en campo o laboratorio. • Medición estable gracias a su diseño ergonómico y protección térmica. • Ideal para monitoreo de salinidad en acuicultura, acuarios marinos, alimentos y más.",
    presentation: "Equipo portátil.No requiere condiciones especiales de almacenamiento."
  },
  {
    id: "prod-531",
    number: 531,
    slug: "termometro",
    name: "TERMÓMETRO",
    category: "equipos",
    subcategory: "general",
    image: "/assets/images/productos/equipos/EQ012.png",
    gallery: ["/assets/images/productos/equipos/EQ012.png"],
    description: "",
    specifications: "Color: amarillo Material: vidrio Tamaño: 150 * 30 * 2mm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ012_ficha.pdf",
    productCode: "EQ012",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "[Información de presentación pendiente]"
  },
  {
    id: "prod-532",
    number: 532,
    slug: "ammo-lock",
    name: "AMMO LOCK",
    category: "equipos",
    subcategory: "general",
    image: "/assets/images/productos/equipos/EQ015.png",
    gallery: ["/assets/images/productos/equipos/EQ015.png"],
    description: "El amonio es un compuesto tóxico para los cultivos acuícolas porque ocasiona: Daños severos en las branquias, problemas en la osmorregulación, desgaste en lo...",
    specifications: "VOLUMEN DE AGUA: 10 galones DOSIS SUGERIDA: 5 mL VOLUMEN DE AGUA: 1 tonelada DOSIS SUGERIDA: 125 mL",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ015_ficha.pdf",
    productCode: "EQ015",
    benefits: "Actúa contrarrestando el efecto de cloro y cloraminas. Está avalado por la Universidad de Georgia, Escuela de Medicina Veterinaria, Departamento de Microbiología Médica.",
    presentation: "Líquido. Envases de: 16 oz"
  },
  {
    id: "prod-533",
    number: 533,
    slug: "freshwater",
    name: "FRESHWATER",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ014.png",
    gallery: ["/assets/images/productos/equipos/EQ014.png"],
    description: "Kit multiparámetros, rápido y fácil de usar.",
    specifications: "[Especificaciones pendientes de completar]",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ014_ficha.pdf",
    productCode: "EQ014",
    benefits: "Permite al productor acuícola mantener el control de los metabolitos tóxicos más perjudiciales dentro de su cultivo. Recomendado para agua dulce.",
    presentation: "Kit de 7 envases de 37 ML cada uno."
  },
  {
    id: "prod-534",
    number: 534,
    slug: "chemetrics-kit-de-peroxido-de-hidrogeno",
    name: "CHEMETRICS KIT DE PERÓXIDO DE HIDRÓGENO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ016.png",
    gallery: ["/assets/images/productos/equipos/EQ016.png"],
    description: "Este kit de valoración de peróxido de hidrógeno viene en una caja de cartón y contiene todo lo necesario para realizar 30 pruebas: treinta ampollas con conju...",
    specifications: "Rango: 0.1 - 1.0%",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ016_ficha.pdf",
    productCode: "EQ016",
    benefits: "• Titulantes de un solo uso sellados y confiables • Procedimiento rápido y sencillo: no es necesario contar las gotas • No se necesitan buretas ni otros equipos • Se puede realizar la titulación en cualquier lugar",
    presentation: "30 ampollas"
  },
  {
    id: "prod-535",
    number: 535,
    slug: "chemetrics-kit-de-nitrito",
    name: "CHEMETRICS KIT DE NITRITO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ017.png",
    gallery: ["/assets/images/productos/equipos/EQ017.png"],
    description: "El kit de prueba para nitrito CHEMets emplea el método de formación de tinte. En una solución acídica, el nitrito diazotiza con una amina aromática primaria ...",
    specifications: "Rango: 0 - 0.1 & 0 - 1",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ017_ficha.pdf",
    productCode: "EQ017",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 pruebas: Comparadores de rango bajo y alto, Solución acidificante, vaso de muestra de 25 mL e instrucciones."
  },
  {
    id: "prod-536",
    number: 536,
    slug: "chemetrics-kit-de-nitrato",
    name: "CHEMETRICS KIT DE NITRATO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ018.png",
    gallery: ["/assets/images/productos/equipos/EQ018.png"],
    description: "El kit de prueba para nitrato emplea el método de reducción de cadmio. El nitrato se reduce a nitrito en presencia de cadmio. En una solución acídica, el nit...",
    specifications: "Rango: 0 - 4.5ppm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ018_ficha.pdf",
    productCode: "EQ018",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 pruebas: recambio, comparador, vaso de muestra de 25 ml, tubo de reacción con tapa e instrucciones."
  },
  {
    id: "prod-537",
    number: 537,
    slug: "chemetrics-kit-de-hierro",
    name: "CHEMETRICS KIT DE HIERRO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ019.png",
    gallery: ["/assets/images/productos/equipos/EQ019.png"],
    description: "El método de análisis de hierro emplea la química de la fenantrolina. El hierro ferroso reacciona con fenantrolina para formar un complejo de color anaranjad...",
    specifications: "Rango: 0 - 0.1 & 0 - 1",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ019_ficha.pdf",
    productCode: "EQ019",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 pruebas: recambio, comparadores de rango bajo y alto, solución activadora, vaso de muestra de 25 ml e instrucciones."
  },
  {
    id: "prod-538",
    number: 538,
    slug: "chemetrics-kit-de-amonio",
    name: "CHEMETRICS KIT DE AMONIO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ020.png",
    gallery: ["/assets/images/productos/equipos/EQ020.png"],
    description: "Kit de Amonio Chemetrics, permite realizar pruebas para determinar concentraciones de amoníaco, son aplicables para acuarios, piscinas camaroneras, efluentes...",
    specifications: "El kit emplea la nesslerización directa. En una solución sumamente alcalina, el amoníaco reacciona con reactivo de Nessler (K2HgI4) para producir un complejo de color amarillo en proporción directa a la concentración de amoníaco.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ020_ficha.pdf",
    productCode: "EQ020",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 ampollas"
  },
  {
    id: "prod-539",
    number: 539,
    slug: "chemetrics-kit-de-fosfato",
    name: "CHEMETRICS KIT DE FOSFATO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ021.png",
    gallery: ["/assets/images/productos/equipos/EQ021.png"],
    description: "El kit de prueba para fosfato emplea la química del cloruro de estaño. En una solución acídica, el ortofosfato reacciona con el molibdato de amonio para form...",
    specifications: "Rango: 0 - 0.1 & 0 - 1",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ021_ficha.pdf",
    productCode: "EQ021",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 pruebas: comparadores de rango bajo y alto, solución activadora, vaso de muestra de 25 ml, tapa del vaso de muestra e instrucciones."
  },
  {
    id: "prod-540",
    number: 540,
    slug: "chemetrics-kit-de-sulfito",
    name: "CHEMETRICS KIT DE SULFITO ",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ022.png",
    gallery: ["/assets/images/productos/equipos/EQ022.png"],
    description: "Los kits de prueba para sulfito emplean la químíca yodométrica. En una solución acídica, el sulfito se titula con un titulador de yoduro-yodato y un indicado...",
    specifications: "Rango: 0 - 0.1 & 0 - 1",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ022_ficha.pdf",
    productCode: "EQ022",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "30 pruebas: treinta ampollas con conjuntos de válvulas, solución neutralizadora, titulador, vaso de muestra de 25 ml e instrucciones."
  },
  {
    id: "prod-541",
    number: 541,
    slug: "chemetrics-kit-de-dureza",
    name: "CHEMETRICS KIT DE DUREZA",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ023.png",
    gallery: ["/assets/images/productos/equipos/EQ023.png"],
    description: "La dureza es una medida del contenido mineral del agua. El calcio y el magnesio son los minerales más comunes que contribuyen a la dureza. El método para la ...",
    specifications: "Rango: 20 - 200ppm / Rango: 10 - 1000ppm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ023_ficha.pdf",
    productCode: "EQ023",
    benefits: "• Titulantes de un solo uso sellados y confiables • Procedimiento rápido y sencillo: no es necesario contar las gotas • No se necesitan buretas ni otros equipos • Se puede realizar la titulación en cualquier lugar • El reactivo es estable • Vida útil de 8 meses",
    presentation: "30 pruebas por titulación: treinta ampollas con conjun- tos de válvulas, titulador, vaso de muestra de 25 ml e instrucciones. Los resulta- dos se expresan como ppm (mg/L) de CaCO3."
  },
  {
    id: "prod-542",
    number: 542,
    slug: "chemetrics-kit-de-alcalinidad-total",
    name: "CHEMETRICS KIT DE ALCALINIDAD TOTAL",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ024.png",
    gallery: ["/assets/images/productos/equipos/EQ024.png"],
    description: "Las pruebas de alcalinidad total de CHEMETRICS determinan el total usando un valorante de ácido clorhídrico y un indicador verde de bromocresol/rojo de metil...",
    specifications: "[Especificaciones pendientes de completar]",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ024_ficha.pdf",
    productCode: "EQ024",
    benefits: "• Titulantes de un solo uso sellado y confiable. • Procedimiento rápido y sencillo: no es necesario contar las gotas. • No se necesitan buretas ni otros equipos. • Se puede realizar una titulación en cualquier lugar. • Apagado automático",
    presentation: "30 pruebas de titulación de alcalinidad total: treinta ampollas con conjuntos de válvulas, solución activadora, titulador, vaso de muestra de 25 ml e instrucciones."
  },
  {
    id: "prod-543",
    number: 543,
    slug: "chemetrics-kit-de-dioxido-de-carbono",
    name: "CHEMETRICS KIT DE DIÓXIDO DE CARBONO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ025.png",
    gallery: ["/assets/images/productos/equipos/EQ025.png"],
    description: "El dióxido de carbono (CO2) disuelto está presente de forma natural como resultado de la respiración animal, la descomposición de la materia orgánica, y la d...",
    specifications: "Rango: 10 - 1000ppm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ025_ficha.pdf",
    productCode: "EQ025",
    benefits: "• Titulantes de un solo uso sellados y confiables • Procedimiento rápido y sencillo: no es necesario contar las gotas no se necesitan buretas ni otros equipos • Se puede realizar la titulación en cualquier lugar",
    presentation: "30 pruebas y contiene treinta ampollas con conjunto de válvula."
  },
  {
    id: "prod-544",
    number: 544,
    slug: "kits-api-nitrato",
    name: "KITS API NITRATO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ026.png",
    gallery: ["/assets/images/productos/equipos/EQ026.png"],
    description: "Los altos niveles de nitrato en su acuario indican una acumulación de desechos de pescado y compuestos orgánicos, lo que resulta en una calidad del agua defi...",
    specifications: "Use el Kit de prueba de nitrato API® para asegurarse de que los niveles de nitrato en su tanque sean seguros y saludables para sus peces. El Nitrate Test Kit lee parámetros de 0 a 160 ppm y contiene 2 frascos de reactivo de prueba líquido, 2 tarjetas de color para facilitar la comparación, 1 tubo de vidrio con tapa hermética e instrucciones paso a paso sobre cómo corregir condiciones inseguras.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ026_ficha.pdf",
    productCode: "EQ026",
    benefits: "Se puede usar tanto para acuarios frescos como para acuarios de agua salada.",
    presentation: "Contiene 90 pruebas e incluye 2 soluciones de prueba, instrucciones fáciles de usar, tubo de prueba de vidrio y carta de colores."
  },
  {
    id: "prod-545",
    number: 545,
    slug: "kits-api-nitrito",
    name: "KITS API NITRITO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ027.png",
    gallery: ["/assets/images/productos/equipos/EQ027.png"],
    description: "El nitrito se produce en el acuario en forma de desechos de pescado, alimentos no consumidos y bacterias nitrificantes en el ciclo natural de su acuario, ya ...",
    specifications: "El kit de prueba de nitrito API® lee los niveles de nitrito de forma rápida y precisa en su tanque y prueba los parámetros de 0 a 5 ppm.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ027_ficha.pdf",
    productCode: "EQ027",
    benefits: "Se puede usar tanto para acuarios frescos como para acuarios de agua salada.",
    presentation: "Contiene 180 pruebas e incluye 1 solución de prueba, instrucciones fáciles de usar, tubo de prueba de vidrio y carta de colores."
  },
  {
    id: "prod-546",
    number: 546,
    slug: "kits-api-fosfato",
    name: "KITS API FOSFATO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ028.png",
    gallery: ["/assets/images/productos/equipos/EQ028.png"],
    description: "El fosfato puede ingresar a su acuario a través del agua del grifo, desechos de peces y sustancias orgánicas en descomposición, como alimentos no consumidos ...",
    specifications: "El KIT DE PRUEBA DE FOSFATO API prueba los niveles de fosfato de 0 a 10 ppm para que pueda controlar fácilmente el estado del agua de su acuario.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ028_ficha.pdf",
    productCode: "EQ028",
    benefits: "Se puede usar tanto para acuarios frescos como para acuarios de agua salada.",
    presentation: "Contiene 150 pruebas e incluye 2 soluciones de prueba, instrucciones fáciles de usar, tubo de ensayo y 2 tablas de colores."
  },
  {
    id: "prod-547",
    number: 547,
    slug: "kits-api-amonio",
    name: "KITS API AMONIO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ029.png",
    gallery: ["/assets/images/productos/equipos/EQ029.png"],
    description: "El kit de prueba de amoníaco API® mide el amoníaco para ayudar a prevenir la pérdida de peces, ya que el amoníaco es el principal factor estresante y mortal ...",
    specifications: "El API Ammonia Test Kit es una prueba de salicilato libre de mercurio para peces de agua dulce y salada, y niveles de niveles de amoníaco de 0 a 8 ppm.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ029_ficha.pdf",
    productCode: "EQ029",
    benefits: "Se puede usar tanto para acuarios frescos como para acuarios de agua salada.",
    presentation: "Contiene 130 pruebas e incluye 2 soluciones de prueba, instrucciones fáciles de usar, tubo de prueba de vidrio y 2 tablas de colores."
  },
  {
    id: "prod-548",
    number: 548,
    slug: "kits-api-calcio",
    name: "KITS API CALCIO",
    category: "equipos",
    subcategory: "kits_analisis",
    image: "/assets/images/productos/equipos/EQ030.png",
    gallery: ["/assets/images/productos/equipos/EQ030.png"],
    description: "El calcio es uno de los elementos más importantes en un acuario de arrecife. Los invertebrados de los arrecifes, como los corales, crustáceos, moluscos e inc...",
    specifications: "El KIT DE PRUEBA DE CALCIO API mide niveles de calcio tan bajos como 20mg/L para ayudarle a mantener saludables a los habitantes de su arrecife.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ030_ficha.pdf",
    productCode: "EQ030",
    benefits: "Se puede usar tanto para acuarios frescos como para acuarios de agua salada.",
    presentation: "Contiene 2 frascos de prueba, instrucciones fáciles de usar y un tubo de ensayo."
  },
  {
    id: "prod-549",
    number: 549,
    slug: "mallas-para-piscinas-camaroneras",
    name: "MALLAS PARA PISCINAS CAMARONERAS",
    category: "equipos",
    subcategory: "mallas",
    image: "",
    gallery: [],
    description: "Mallas sintéticas de alta resistencia diseñadas para aplicaciones en acuicultura. Fabricadas con polímeros de calidad, son resistentes a bacterias, duraderas...",
    specifications: "Material: Polímero Color: Negro Configuración: Malla rómbica (refuerzo en modelos 5277 y 5255) Protección UV: Sí Resistencia bacteriana: Alta Presentaciones de malla: Malla 5277: 1x1 mm Malla 5255: 3x3 mm Malla 5201: 4x4 mm Malla 5256: 6x6 mm",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ041_ficha.pdf",
    productCode: "EQ041",
    benefits: "Alta durabilidad y resistencia mecánica. Protección contra exposición prolongada al sol gracias a su tratamiento UV. Diseño antibacteriano que previene acumulaciones nocivas. Fácil de cortar e instalar en sistemas de filtrado, protección de tanques o esclusas. Versatilidad de calibres según la necesidad del cultivo o instalación.",
    presentation: "Presentación por metraje: Malla 5277: Rollos de 50 metros Mallas 5255, 5201, 5256: Rollos de 25 metros Peso del rollo: Aproximadamente 16,8 kg Almacenamiento: Mantener en lugar seco, alejado de fuentes de calor y rayos solares cuando no esté en uso. Puede almacenarse en posición vertical u horizontal sin riesgo de deformación."
  },
  {
    id: "prod-550",
    number: 550,
    slug: "malla-marines-roja",
    name: "MALLA MARINES ROJA",
    category: "equipos",
    subcategory: "mallas",
    image: "",
    gallery: [],
    description: "Malla técnica de alto rendimiento elaborada con 100% poliéster texturizado, teñida por agotamiento, de color rojo. Ideal para aplicaciones en acuicultura, fi...",
    specifications: "Artículo: Marines Composición: 100% Poliéster texturizado Ancho: 1,60 m Micraje: 800 - 900 micras Rendimiento: Aproximadamente 15 metros por kilo Proceso de tintura: Por agotamiento Proceso de lavado: No dejar en remojo con detergentes Color: Rojo",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ042_ficha.pdf",
    productCode: "EQ042",
    benefits: "Alta resistencia y durabilidad gracias a su composición de poliéster texturizado. Excelente rendimiento: mayor cobertura por kilo. Teñida por agotamiento, lo que asegura color uniforme y buena fijación. Ideal para sistemas de filtración, sombreado o contención en ambientes húmedos o exigentes. Fácil de manejar y cortar.",
    presentation: "Presentación: Rollos de 200 metros Comercialización: Por metro lineal Almacenamiento: Guardar en lugar seco, protegido del sol directo y de humedad excesiva para conservar su color y estructura."
  },
  {
    id: "prod-551",
    number: 551,
    slug: "mallas-nitex",
    name: "MALLAS NITEX",
    category: "equipos",
    subcategory: "mallas",
    image: "",
    gallery: [],
    description: "Mallas de precisión fabricadas con monofilamento sintético especializado, diseñadas para garantizar consistencia en la filtración. Son resistentes a bacteria...",
    specifications: "Material: Monofilamento sintético Tipo de tejido: Tejido de precisión Resistencia química: Alta (bacterias, limpiadores, ácidos, insectos) Propiedades destacadas: Tamaño de poro constante Grosor definido Alta resistencia a la tracción Estabilidad dimensional Facilidad de limpieza MICRAJES DISPONIBLES: 75 micras 100 micras 200 micras 300 micras 400 micras 600 micras 1000 micras",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ043_ficha.pdf",
    productCode: "EQ043",
    benefits: "Permite una filtración precisa y repetible No se deforma ni pierde estructura en uso prolongado Alta resistencia a agentes químicos y al desgaste Facilita la limpieza y el mantenimiento Compatible con procesos de bioseguridad exigentes",
    presentation: "Presentación: Venta por metros lineales Almacenamiento: Mantener en lugar seco, limpio y protegido de la luz solar directa para preservar su integridad estructural y micraje."
  },
  {
    id: "prod-552",
    number: 552,
    slug: "tirillas-ph",
    name: "TIRILLAS ph",
    category: "equipos",
    subcategory: "medidores",
    image: "/assets/images/productos/equipos/EQ033.png",
    gallery: ["/assets/images/productos/equipos/EQ033.png"],
    description: "",
    specifications: "[Especificaciones pendientes de completar]",
    datasheetUrl: "",
    productCode: "EQ033",
    benefits: "[Beneficios pendientes de completar]",
    presentation: "Rango pH: 4.5 - 10.0 Envase de plástico."
  },
  {
    id: "prod-553",
    number: 553,
    slug: "camara-neubauer",
    name: "CÁMARA NEUBAUER",
    category: "equipos",
    subcategory: "opticos",
    image: "/assets/images/productos/equipos/EQ032.png",
    gallery: ["/assets/images/productos/equipos/EQ032.png"],
    description: "Cámara de Neubauer o hemocitómetro es un instrumento para realizar el recuento de esporas y células en un medio líquido.",
    specifications: "El cálculo de la concentración de células se puede expresar así: - Partículas / μl = (partículas contadas) / [ (superficie contada (mm²) profundidad de la cámara (mm) ] dilución.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ032_ficha.pdf",
    productCode: "EQ032",
    benefits: "Esta cámara de recuento está adaptada al microscopio de campo claro o al de contraste de fases. Se cubre la cámara con un cubreobjetos que se adhiere por simple tensión superficial (en especial una vez que se haya añadido la muestra líquida).",
    presentation: "[Información de presentación pendiente]"
  },
  {
    id: "prod-554",
    number: 554,
    slug: "camara-sedgewick",
    name: "CÁMARA SEDGEWICK",
    category: "equipos",
    subcategory: "opticos",
    image: "/assets/images/productos/equipos/EQ034.png",
    gallery: ["/assets/images/productos/equipos/EQ034.png"],
    description: "Cámara de recuento Sedgewick Rafter para contar partículas y microorganismos en 1 ml de agua u otros líquidos transparentes.",
    specifications: "- La cámara de 50 x 20 x 1 mm (= 1 cm³) es graduada con un retículo de 1 mm que subdivide 1 ml en 1000 μl. - Entrega con un cubreobjetos aprox. 60 x 30 x 1 mm - No se necesita el retículo para muchas aplicaciones, sobre todo para métodos APHA y al analizar grandes especies de plancton. - Es apta para el uso con microscopios convencionales y microscopios invertidos. - Se puede usar en combinación con micrómetros oculares.",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ034_ficha.pdf",
    productCode: "EQ034",
    benefits: "- Diseñadas para facilitar el recuento de grandes cantidades de zooplancton. - El pequeño tamaño de nuestras cámaras, hace que sean aptas para utilizarse en microscopio estereoscópico.",
    presentation: "[Información de presentación pendiente]"
  },
  {
    id: "prod-555",
    number: 555,
    slug: "oxigenometro-oakton-260",
    name: "OXIGENÓMETRO - OAKTON 260",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ001.png",
    gallery: ["/assets/images/productos/equipos/EQ001.png"],
    description: "Medidor portátil de oxígeno disuelto y temperatura, diseñado con una carcasa robusta, antideslizante y resistente al agua (IP67), polvo e impactos. Su diseño...",
    specifications: "Características Principales • Carcasa antideslizante y resistente (IP67) • Pantalla LCD monocromática con retroiluminación • Registro de hasta 1000 datos • Conectividad USB y RS-232 Datos Técnicos • Oxígeno disuelto: 0–20 mg/L, precisión ±0.1 mg/L • Temperatura: -30 a 130 °C, precisión ±0.5 °C • Resolución: 0.01 mg/L y 0.1 °C • Alimentación: 2 baterías AA",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ001_ficha.pdf",
    productCode: "EQ001",
    benefits: "Mide con precisión parámetros esenciales como OD y temperatura • Ideal para condiciones exigentes de campo y laboratorio • Permite trazabilidad de datos con su función de registro digital • Fácil de usar, transportar y configurar",
    presentation: "Equipo portátil con cable de 2 m, portaelectrodos y soporte plegable. No requiere refrigeración ni almacenamiento especial."
  },
  {
    id: "prod-556",
    number: 556,
    slug: "neon-optod",
    name: "NEON OPTOD",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ003.png",
    gallery: ["/assets/images/productos/equipos/EQ003.png"],
    description: "Oxímetro portátil de alta precisión para medición de oxígeno disuelto y temperatura en sistemas acuícolas. Utiliza sensor OPTOD con tecnología óptica de lumi...",
    specifications: "Características Principales • Medición de oxígeno en mg/L, ppm y % de saturación • Sensor óptico OPTOD de bajo mantenimiento (cambio cada 2 años) • Almacenamiento interno de 3000 registros, descarga por WiFi • Apagado automático, zoom, y visualización avanzada Datos Técnicos • Rango de oxígeno: 0,00 – 20,00 mg/L / 0 – 200 % • Resolución: 0,01 • Precisión: ±0,1 mg/L, ±0,1 %, ±0,5 °C • Compensaciones: Barométrica (auto), Salinidad (manual), Temperatura (auto)",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ003_ficha.pdf",
    productCode: "EQ003",
    benefits: "Lecturas confiables y precisas incluso en condiciones con baja circulación de agua • Bajo mantenimiento y operación sin consumo de oxígeno • Gestión completa de datos y usuarios directamente desde el sensor • Ideal para mediciones de campo gracias a su portabilidad y autonomía",
    presentation: "Equipo portátil alimentado con 3 pilas AA. Incluye sensor OPTOD. Datos exportables vía WiFi. No requiere condiciones especiales de almacenamiento."
  },
  {
    id: "prod-557",
    number: 557,
    slug: "oxigenometro-oxyguard-polaris-c",
    name: "OXIGENÓMETRO OxyGuard Polaris C",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ004.png",
    gallery: ["/assets/images/productos/equipos/EQ004.png"],
    description: "Oxímetro portátil de campo con sonda galvánica que permite medir oxígeno disuelto (en mg/L y % de saturación), temperatura y compensación de salinidad. Diseñ...",
    specifications: "Características Principales • Medición de oxígeno (ppm / % saturación) y temperatura • Calibración automática con verificación de estabilidad • Compensación automática de temperatura y presión atmosférica • Apagado automático para ahorro de energía • Pantalla amplia con retroiluminación • Incluye clip desmontable para sujetar al cinturón o portapapeles • Opera hasta los 4000 msnm • Batería de 9V con duración de hasta 1.400 horas • Incluye membrana y solución estándar (electrolito) Datos Técnicos • Rango de oxígeno: 0 – 60 ppm • Rango de temperatura: -5 °C a +45 °C • Longitud del cable: 3 m y 8 m disponibles",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ004_ficha.pdf",
    productCode: "EQ004",
    benefits: "• Equipamiento confiable para uso en campo y ambientes de cultivo exigentes • Lecturas precisas gracias a su compensación barométrica y de temperatura • Alta autonomía y facilidad de transporte para jornadas prolongadas • Calibración automática que simplifica el manejo y reduce errores",
    presentation: "Dispositivo portátil con sonda galvánica, clip desmontable, batería de 9V, membrana y solución electrolítica. No requiere condiciones especiales de almacenamiento."
  },
  {
    id: "prod-558",
    number: 558,
    slug: "medidor-de-ph",
    name: "MEDIDOR DE PH",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ006.png",
    gallery: ["/assets/images/productos/equipos/EQ006.png"],
    description: "",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a golpes y caídas • Lectura directa con muestra mínima (0.3 ml) • Calibración sencilla con solo dos botones • Pantalla LCD retroiluminada • Sensor reemplazable • Apagado automático (30 min) • Indicador de batería baja Funciones • Reconocimiento automático de buffer • Compensación automática de temperatura • Calibración de temperatura • Auto Hold / Estabilización automática • Apagado automático • Indicador de batería baja Construcción y Alimentación • Material: Carcasa Epoxi ABS, sensor plano • Dimensiones: 164 x 29 x 20 mm • Peso: Aprox. 55 g (con sensor y baterías) • Alimentación: 2 baterías CR2032 • Autonomía: Aprox. 400 h sin retroiluminación",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ006_ficha.pdf",
    productCode: "EQ006",
    benefits: "A prueba de agua y polvo, resistente a golpes. - Peso 55 gramos. - Pantalla amplia LCD con retroiluminación para ver resultados en lugares obscuros. - Se necesita un volumen mínimo de muestra. - Solo dos botones de calibración. - Material de la carcaza de polímero Epoxi ABS.",
    presentation: "- Soluciones de calibración pH 7.00 & 4.01 (14 ml cada uno). - Baterías CR2032 (2). - Pipeta. - Manual de instrucción y manual rápido. - Estuche."
  },
  {
    id: "prod-559",
    number: 559,
    slug: "medidor-de-potasio",
    name: "MEDIDOR DE POTASIO",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ007.png",
    gallery: ["/assets/images/productos/equipos/EQ007.png"],
    description: "Medidor portátil japonés de potasio de alta precisión, ideal para laboratorio y campo. Utiliza tecnología de electrodo selectivo de iones, requiere un volume...",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a golpes y caídas • Lectura directa con muestra mínima (0.3 ml) • Calibración sencilla con solo dos botones • Pantalla LCD retroiluminada • Sensor reemplazable • Apagado automático (30 min) • Indicador de batería baja Funciones • Reconocimiento automático de buffer • Compensación automática de temperatura • Calibración de temperatura • Auto Hold / Estabilización automática • Apagado automático • Indicador de batería baja Construcción y Alimentación • Material: Carcasa Epoxi ABS, sensor plano • Dimensiones: 164 x 29 x 20 mm • Peso: Aprox. 55 g (con sensor y baterías) • Alimentación: 2 baterías CR2032 • Autonomía: Aprox. 400 h sin retroiluminación",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ007_ficha.pdf",
    productCode: "EQ007",
    benefits: "• Alta portabilidad y fácil operación en campo o laboratorio. • Requiere una cantidad mínima de muestra para análisis rápidos. • Precisión confiable para decisiones inmediatas en acuicultura, agricultura o control de calidad. • Larga duración de batería y resistente a condiciones adversas.",
    presentation: "Incluye estuche, soluciones de calibración de 150 y 2000 ppm (14 ml c/u), 2 baterías CR2032, 2 jeringas de 2.5 ml y manual de instrucciones."
  },
  {
    id: "prod-560",
    number: 560,
    slug: "medidor-de-conductividad-ec-11",
    name: "MEDIDOR DE CONDUCTIVIDAD EC-11",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ008.png",
    gallery: ["/assets/images/productos/equipos/EQ008.png"],
    description: "Medidor portátil compacto y de alta precisión diseñado para la medición de conductividad en campo o laboratorio. Su tecnología de doble electrodo bipolar y f...",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a golpes y caídas • Pantalla LCD amplia y retroiluminada • Requiere volumen mínimo de muestra: 0.12 ml • Sensor plano y reemplazable • Apagado automático (30 min) • Indicador de batería baja Construcción y Alimentación • Material: Carcasa Epoxi ABS • Pantalla: LCD monocromática con retroiluminación • Dimensiones: 164 × 29 × 20 mm • Peso: Aprox. 55 g (incluyendo baterías y sensor) • Alimentación: 2 baterías CR2032 • Duración: Aprox. 400 horas de uso continuo sin retroiluminación",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ008_ficha.pdf",
    productCode: "EQ008",
    benefits: "Lectura rápida y precisa de conductividad con una muestra mínima. • Portátil, confiable y resistente para uso en campo o laboratorio. • Automatizaciones que simplifican la operación sin comprometer la precisión. • Ideal para controlar la calidad del agua en cultivos acuícolas, agrícolas o análisis industriales.",
    presentation: "Soluciones de calibración: 1,41 mS/cm y 12,9 mS/cm (14 ml c/u) • Solución de tratamiento de electrodo (4 ml) • 2 baterías CR2032 • Pipeta • Manual de instrucciones • Estuche portátil"
  },
  {
    id: "prod-561",
    number: 561,
    slug: "medidor-de-calcio",
    name: "MEDIDOR DE CALCIO",
    category: "equipos",
    subcategory: "oxigenometros",
    image: "/assets/images/productos/equipos/EQ009.png",
    gallery: ["/assets/images/productos/equipos/EQ009.png"],
    description: "Medidor portátil de calcio con electrodo selectivo de iones, diseñado para ofrecer mediciones rápidas y precisas en campo o laboratorio. Su diseño compacto y...",
    specifications: "Características Principales • A prueba de agua y polvo (IP67) • Resistente a golpes • Pantalla LCD con retroiluminación para condiciones de baja luz • Sensor reemplazable • Auto Hold y estabilización automática • Apagado automático (30 min) • Indicador de batería baja Construcción y Alimentación • Material: Carcasa Epoxi ABS / Sensor plano • Pantalla: LCD digital monocromática con retroiluminación • Dimensiones: 164 × 29 × 20 mm • Peso: Aprox. 55 g (incluyendo baterías y sensor) • Alimentación: 2 baterías CR2032 • Duración: Aprox. 400 horas de uso continuo sin retroiluminación",
    datasheetUrl: "/assets/pdfs/productos/equipos/EQ009_ficha.pdf",
    productCode: "EQ009",
    benefits: "• Permite análisis precisos de calcio con solo unas gotas de muestra. • Ideal para monitoreo directo en campo o laboratorio. • Portátil, práctico y con alta resistencia al agua, polvo y golpes. • Fácil de usar, con calibración simple y rápida.",
    presentation: "• Soluciones de calibración: 150 y 2000 ppm (14 ml c/u) • 2 baterías CR2032 • Jeringa dosificadora (2.5 ml) • Manual de instrucciones • Estuche rígido de transporte"
  }
];
